---
title: "Sierra Leone 2"
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(tidyr)
library(checkmate)
library(maptools)
library(rgdal)
library(ggplot2)
library(knitr)
gpclibPermit()
library(DT)
```


```{r,include=FALSE}
 my_vars <- data.frame(
   variable = c("market_open", "price_rice", "aware", "water"),
   family = c("Markets", "Markets", "Actions", "Actions"),
   short_label = c("Is market open?", "Price of a rice", "Aware of Covid19", "Access to water"),
   description = c("details on market open", "Price of a cup of rice", "Details on aware of Covid19", "Details on access to water"),
   min = c(-2, -1, 0, NA),
   stringsAsFactors = FALSE
 )

my_data <-
   expand_grid(id = c("Bo", "Bombali", "Bonthe"), date = as.Date(c("2020-04-18", "2020-04-19", "2020-04-20"))) %>%
   data.frame(stringsAsFactors = FALSE) %>%
     mutate(n = 3) %>%
     uncount(n) %>%
     dplyr::mutate(
     market_open	 = rbinom(n(), 1, .5),
     price_rice	 = rbinom(n(), 1, .5),
     aware	 = rbinom(n(), 1, .5),
     water	 = rbinom(n(), 1, .5)) %>%
     distinct()


my_args <- data.frame(
  intro_text = "Intro text",
  intro_note = "Lots of great people worked on this. More information here: ...",
  data_note = "Study specific note about data source",
  map_path = paste0(getwd(), '/shapefiles'),
  map_layer = "SLE_adm3",
  map_region =  "NAME_2",
  group = "District",
  scale_vars = TRUE,
  stringsAsFactors = FALSE
)


dashdash::dashdash(
  output_file ="/Users/lilymedina/Documents/GitHub/metadash/surveys/sl2.html",
  title = "A sample dashboard for my study",
  subtitle = "What's special about this study",
  map_path = "shapefiles",
  my_data = my_data,
  my_vars = my_vars,
  my_args = my_args)
```



<embed type="text/html" src="surveys/sl2.html" width="800" height="800">
